### ISSUE TITLE
CRUD com Express

### ISSUE THREAD

**Issue by rodrigoms2004** [jonathansilva/API#1]
Opa
Como não tinha o seu e-mail de contato eu abri essa issue aqui.
Peguei o seu código e em vez de usar cors eu usei express.

Nele eu permito a criação do usuário, com a criptografia da senha, assim como você fez, mas ele só recebe o token quando loga, e com esse token ele pode fazer CRUD numa tabela chamada toDoList.

O que deu trabalho foi o update, sacanagem do Knex, pois quando ele constrói a query acaba colocando um campo isEmpty do nada! 

`update `toDoList` set `done` = true, `finish` = '1547485703', `isEmpty` = (select *) where `id` = '5'`

Para resolver essa joça o objeto de update tem que possuir a propriedade isEmpty setada como **undefined**

_server/models/todoModel.js_
```
        const todoDone = {
            done: true,
            finish: body.finish,
            isEmpty: undefined      
        }
```

Desse jeito ele funciona, como voce pode ver q query abaixo:
`update `toDoList` set `done` = true, `finish` = '1547485703' where `id` = '5'`

Bem, agradeço pelo código, e espero que a minha versão seja útil para você

[nodeAPI-JWT](https://github.com/rodrigoms2004/nodeAPI-JWT)

Abraço

**Comment by jonathansilva** [comment]
@rodrigoms2004 não entendi essa do Knex adicionando isEmpty
Aqui o update funciona normal
